// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/pb/users/users.proto

package users_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UsersGetPasswordRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersGetPasswordRequest) Reset()         { *m = UsersGetPasswordRequest{} }
func (m *UsersGetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*UsersGetPasswordRequest) ProtoMessage()    {}
func (*UsersGetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a956228a9a6c5fd3, []int{0}
}

func (m *UsersGetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersGetPasswordRequest.Unmarshal(m, b)
}
func (m *UsersGetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersGetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *UsersGetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersGetPasswordRequest.Merge(m, src)
}
func (m *UsersGetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_UsersGetPasswordRequest.Size(m)
}
func (m *UsersGetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersGetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UsersGetPasswordRequest proto.InternalMessageInfo

func (m *UsersGetPasswordRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type UsersGetPasswordResponse struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersGetPasswordResponse) Reset()         { *m = UsersGetPasswordResponse{} }
func (m *UsersGetPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*UsersGetPasswordResponse) ProtoMessage()    {}
func (*UsersGetPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a956228a9a6c5fd3, []int{1}
}

func (m *UsersGetPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersGetPasswordResponse.Unmarshal(m, b)
}
func (m *UsersGetPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersGetPasswordResponse.Marshal(b, m, deterministic)
}
func (m *UsersGetPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersGetPasswordResponse.Merge(m, src)
}
func (m *UsersGetPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_UsersGetPasswordResponse.Size(m)
}
func (m *UsersGetPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersGetPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UsersGetPasswordResponse proto.InternalMessageInfo

func (m *UsersGetPasswordResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UsersGetPasswordResponse) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UsersCreateRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Firstname            string   `protobuf:"bytes,3,opt,name=Firstname,proto3" json:"Firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,4,opt,name=Lastname,proto3" json:"Lastname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersCreateRequest) Reset()         { *m = UsersCreateRequest{} }
func (m *UsersCreateRequest) String() string { return proto.CompactTextString(m) }
func (*UsersCreateRequest) ProtoMessage()    {}
func (*UsersCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a956228a9a6c5fd3, []int{2}
}

func (m *UsersCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersCreateRequest.Unmarshal(m, b)
}
func (m *UsersCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersCreateRequest.Marshal(b, m, deterministic)
}
func (m *UsersCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersCreateRequest.Merge(m, src)
}
func (m *UsersCreateRequest) XXX_Size() int {
	return xxx_messageInfo_UsersCreateRequest.Size(m)
}
func (m *UsersCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UsersCreateRequest proto.InternalMessageInfo

func (m *UsersCreateRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UsersCreateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UsersCreateRequest) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *UsersCreateRequest) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

type UsersCreateResponse struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersCreateResponse) Reset()         { *m = UsersCreateResponse{} }
func (m *UsersCreateResponse) String() string { return proto.CompactTextString(m) }
func (*UsersCreateResponse) ProtoMessage()    {}
func (*UsersCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a956228a9a6c5fd3, []int{3}
}

func (m *UsersCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersCreateResponse.Unmarshal(m, b)
}
func (m *UsersCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersCreateResponse.Marshal(b, m, deterministic)
}
func (m *UsersCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersCreateResponse.Merge(m, src)
}
func (m *UsersCreateResponse) XXX_Size() int {
	return xxx_messageInfo_UsersCreateResponse.Size(m)
}
func (m *UsersCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UsersCreateResponse proto.InternalMessageInfo

func (m *UsersCreateResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type UsersUpdateRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Firstname            string   `protobuf:"bytes,3,opt,name=Firstname,proto3" json:"Firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,4,opt,name=Lastname,proto3" json:"Lastname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersUpdateRequest) Reset()         { *m = UsersUpdateRequest{} }
func (m *UsersUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UsersUpdateRequest) ProtoMessage()    {}
func (*UsersUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a956228a9a6c5fd3, []int{4}
}

func (m *UsersUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersUpdateRequest.Unmarshal(m, b)
}
func (m *UsersUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersUpdateRequest.Marshal(b, m, deterministic)
}
func (m *UsersUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersUpdateRequest.Merge(m, src)
}
func (m *UsersUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UsersUpdateRequest.Size(m)
}
func (m *UsersUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UsersUpdateRequest proto.InternalMessageInfo

func (m *UsersUpdateRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UsersUpdateRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UsersUpdateRequest) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *UsersUpdateRequest) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

type UsersUpdateResponse struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Firstname            string   `protobuf:"bytes,3,opt,name=Firstname,proto3" json:"Firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,4,opt,name=Lastname,proto3" json:"Lastname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersUpdateResponse) Reset()         { *m = UsersUpdateResponse{} }
func (m *UsersUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UsersUpdateResponse) ProtoMessage()    {}
func (*UsersUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a956228a9a6c5fd3, []int{5}
}

func (m *UsersUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersUpdateResponse.Unmarshal(m, b)
}
func (m *UsersUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersUpdateResponse.Marshal(b, m, deterministic)
}
func (m *UsersUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersUpdateResponse.Merge(m, src)
}
func (m *UsersUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UsersUpdateResponse.Size(m)
}
func (m *UsersUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UsersUpdateResponse proto.InternalMessageInfo

func (m *UsersUpdateResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UsersUpdateResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UsersUpdateResponse) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *UsersUpdateResponse) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

type UsersListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersListRequest) Reset()         { *m = UsersListRequest{} }
func (m *UsersListRequest) String() string { return proto.CompactTextString(m) }
func (*UsersListRequest) ProtoMessage()    {}
func (*UsersListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a956228a9a6c5fd3, []int{6}
}

func (m *UsersListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersListRequest.Unmarshal(m, b)
}
func (m *UsersListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersListRequest.Marshal(b, m, deterministic)
}
func (m *UsersListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersListRequest.Merge(m, src)
}
func (m *UsersListRequest) XXX_Size() int {
	return xxx_messageInfo_UsersListRequest.Size(m)
}
func (m *UsersListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UsersListRequest proto.InternalMessageInfo

type UsersListResponse struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Firstname            string   `protobuf:"bytes,3,opt,name=Firstname,proto3" json:"Firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,4,opt,name=Lastname,proto3" json:"Lastname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersListResponse) Reset()         { *m = UsersListResponse{} }
func (m *UsersListResponse) String() string { return proto.CompactTextString(m) }
func (*UsersListResponse) ProtoMessage()    {}
func (*UsersListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a956228a9a6c5fd3, []int{7}
}

func (m *UsersListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersListResponse.Unmarshal(m, b)
}
func (m *UsersListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersListResponse.Marshal(b, m, deterministic)
}
func (m *UsersListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersListResponse.Merge(m, src)
}
func (m *UsersListResponse) XXX_Size() int {
	return xxx_messageInfo_UsersListResponse.Size(m)
}
func (m *UsersListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UsersListResponse proto.InternalMessageInfo

func (m *UsersListResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UsersListResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UsersListResponse) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *UsersListResponse) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

type UsersByIDRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersByIDRequest) Reset()         { *m = UsersByIDRequest{} }
func (m *UsersByIDRequest) String() string { return proto.CompactTextString(m) }
func (*UsersByIDRequest) ProtoMessage()    {}
func (*UsersByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a956228a9a6c5fd3, []int{8}
}

func (m *UsersByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersByIDRequest.Unmarshal(m, b)
}
func (m *UsersByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersByIDRequest.Marshal(b, m, deterministic)
}
func (m *UsersByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersByIDRequest.Merge(m, src)
}
func (m *UsersByIDRequest) XXX_Size() int {
	return xxx_messageInfo_UsersByIDRequest.Size(m)
}
func (m *UsersByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UsersByIDRequest proto.InternalMessageInfo

func (m *UsersByIDRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type UsersByIDResponse struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Firstname            string   `protobuf:"bytes,3,opt,name=Firstname,proto3" json:"Firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,4,opt,name=Lastname,proto3" json:"Lastname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersByIDResponse) Reset()         { *m = UsersByIDResponse{} }
func (m *UsersByIDResponse) String() string { return proto.CompactTextString(m) }
func (*UsersByIDResponse) ProtoMessage()    {}
func (*UsersByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a956228a9a6c5fd3, []int{9}
}

func (m *UsersByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersByIDResponse.Unmarshal(m, b)
}
func (m *UsersByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersByIDResponse.Marshal(b, m, deterministic)
}
func (m *UsersByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersByIDResponse.Merge(m, src)
}
func (m *UsersByIDResponse) XXX_Size() int {
	return xxx_messageInfo_UsersByIDResponse.Size(m)
}
func (m *UsersByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UsersByIDResponse proto.InternalMessageInfo

func (m *UsersByIDResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UsersByIDResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UsersByIDResponse) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *UsersByIDResponse) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

type UsersDeleteRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersDeleteRequest) Reset()         { *m = UsersDeleteRequest{} }
func (m *UsersDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*UsersDeleteRequest) ProtoMessage()    {}
func (*UsersDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a956228a9a6c5fd3, []int{10}
}

func (m *UsersDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersDeleteRequest.Unmarshal(m, b)
}
func (m *UsersDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersDeleteRequest.Marshal(b, m, deterministic)
}
func (m *UsersDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersDeleteRequest.Merge(m, src)
}
func (m *UsersDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_UsersDeleteRequest.Size(m)
}
func (m *UsersDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UsersDeleteRequest proto.InternalMessageInfo

func (m *UsersDeleteRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type UsersDeleteResponse struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersDeleteResponse) Reset()         { *m = UsersDeleteResponse{} }
func (m *UsersDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*UsersDeleteResponse) ProtoMessage()    {}
func (*UsersDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a956228a9a6c5fd3, []int{11}
}

func (m *UsersDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersDeleteResponse.Unmarshal(m, b)
}
func (m *UsersDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersDeleteResponse.Marshal(b, m, deterministic)
}
func (m *UsersDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersDeleteResponse.Merge(m, src)
}
func (m *UsersDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_UsersDeleteResponse.Size(m)
}
func (m *UsersDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UsersDeleteResponse proto.InternalMessageInfo

func (m *UsersDeleteResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func init() {
	proto.RegisterType((*UsersGetPasswordRequest)(nil), "users_pb.UsersGetPasswordRequest")
	proto.RegisterType((*UsersGetPasswordResponse)(nil), "users_pb.UsersGetPasswordResponse")
	proto.RegisterType((*UsersCreateRequest)(nil), "users_pb.UsersCreateRequest")
	proto.RegisterType((*UsersCreateResponse)(nil), "users_pb.UsersCreateResponse")
	proto.RegisterType((*UsersUpdateRequest)(nil), "users_pb.UsersUpdateRequest")
	proto.RegisterType((*UsersUpdateResponse)(nil), "users_pb.UsersUpdateResponse")
	proto.RegisterType((*UsersListRequest)(nil), "users_pb.UsersListRequest")
	proto.RegisterType((*UsersListResponse)(nil), "users_pb.UsersListResponse")
	proto.RegisterType((*UsersByIDRequest)(nil), "users_pb.UsersByIDRequest")
	proto.RegisterType((*UsersByIDResponse)(nil), "users_pb.UsersByIDResponse")
	proto.RegisterType((*UsersDeleteRequest)(nil), "users_pb.UsersDeleteRequest")
	proto.RegisterType((*UsersDeleteResponse)(nil), "users_pb.UsersDeleteResponse")
}

func init() { proto.RegisterFile("internal/pb/users/users.proto", fileDescriptor_a956228a9a6c5fd3) }

var fileDescriptor_a956228a9a6c5fd3 = []byte{
	// 391 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0x4f, 0x4b, 0xfb, 0x40,
	0x10, 0x25, 0xe9, 0x8f, 0x1f, 0xed, 0x28, 0xa2, 0xeb, 0xc1, 0x12, 0x5b, 0xd0, 0x45, 0xc1, 0x53,
	0x2b, 0x8a, 0x5f, 0x40, 0x43, 0xa5, 0xd2, 0x83, 0x54, 0x7a, 0xf0, 0x24, 0xa9, 0x9d, 0x43, 0xa0,
	0x26, 0x71, 0x77, 0xab, 0x54, 0xef, 0x7e, 0x49, 0xbf, 0x8c, 0x64, 0xff, 0xc4, 0x24, 0x9b, 0x14,
	0x11, 0xec, 0xa5, 0x74, 0x76, 0x66, 0xde, 0xbc, 0xd7, 0x79, 0x53, 0xe8, 0x86, 0x91, 0x40, 0x16,
	0x05, 0xf3, 0x7e, 0x32, 0xed, 0x2f, 0x38, 0x32, 0xae, 0x3e, 0x7b, 0x09, 0x8b, 0x45, 0x4c, 0x9a,
	0x32, 0x78, 0x48, 0xa6, 0xf4, 0x02, 0xf6, 0x26, 0xe9, 0xf7, 0x6b, 0x14, 0xb7, 0x01, 0xe7, 0xaf,
	0x31, 0x9b, 0x8d, 0xf1, 0x79, 0x81, 0x5c, 0x10, 0x0f, 0x9a, 0x69, 0x2a, 0x0a, 0x9e, 0xb0, 0xed,
	0x1c, 0x38, 0x27, 0xad, 0x71, 0x16, 0xd3, 0x01, 0xb4, 0xed, 0x36, 0x9e, 0xc4, 0x11, 0x47, 0xb2,
	0x05, 0xee, 0xd0, 0xd7, 0x1d, 0xee, 0xd0, 0x4f, 0x71, 0x4c, 0x4d, 0xdb, 0x55, 0x38, 0x26, 0xa6,
	0x1f, 0x0e, 0x10, 0x09, 0x74, 0xc5, 0x30, 0x10, 0xf8, 0x83, 0xd1, 0xab, 0xe0, 0x48, 0x07, 0x5a,
	0x83, 0x90, 0x71, 0x21, 0x1b, 0x1b, 0x32, 0xf9, 0xfd, 0x90, 0x76, 0x8e, 0x02, 0x9d, 0xfc, 0xa7,
	0x3a, 0x4d, 0x4c, 0x8f, 0x61, 0xb7, 0xc0, 0xa3, 0x5a, 0x0b, 0x7d, 0xd3, 0x74, 0x27, 0xc9, 0x2c,
	0x47, 0xb7, 0x42, 0x71, 0x46, 0xdf, 0x2d, 0xd1, 0xff, 0x3d, 0xc5, 0x77, 0x4d, 0xd1, 0xcc, 0xae,
	0xff, 0xb9, 0xff, 0x60, 0x38, 0x81, 0x6d, 0x39, 0x7c, 0x14, 0x72, 0xa1, 0x65, 0xd3, 0x25, 0xec,
	0xe4, 0xde, 0xd6, 0x4a, 0x87, 0x6a, 0x3a, 0x97, 0xcb, 0xa1, 0x5f, 0xb3, 0x85, 0x8c, 0x9e, 0xaa,
	0x59, 0x2b, 0xbd, 0x23, 0x6d, 0x13, 0x1f, 0xe7, 0x58, 0x6b, 0x93, 0xcc, 0x73, 0xa6, 0xaa, 0x9a,
	0xe2, 0xd9, 0x67, 0x03, 0x36, 0x65, 0xdd, 0x1d, 0xb2, 0x97, 0xf0, 0x11, 0xc9, 0xbd, 0x16, 0x9f,
	0x3b, 0x3e, 0x72, 0xd8, 0x33, 0x27, 0xdd, 0xab, 0xb9, 0x67, 0x8f, 0xae, 0x2a, 0xd1, 0xb3, 0x6f,
	0x60, 0x23, 0x77, 0x06, 0xa4, 0x53, 0x6a, 0x29, 0x5c, 0xa9, 0xd7, 0xad, 0xc9, 0x96, 0xb0, 0x94,
	0x5f, 0x2d, 0xac, 0xc2, 0x09, 0x59, 0x58, 0x25, 0x93, 0x0f, 0xa0, 0x95, 0x59, 0x8d, 0x78, 0xa5,
	0xda, 0x9c, 0x27, 0xbd, 0xfd, 0xca, 0x9c, 0x42, 0x39, 0x75, 0x88, 0xaf, 0x71, 0x52, 0x4f, 0x58,
	0x38, 0x39, 0x33, 0x59, 0x38, 0x05, 0x13, 0x19, 0x65, 0x6a, 0x71, 0x96, 0xb2, 0xc2, 0xd6, 0x2d,
	0x65, 0xc5, 0x6d, 0x4f, 0xff, 0xcb, 0x7f, 0xe4, 0xf3, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x59,
	0x8d, 0x72, 0x0e, 0xb2, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UsersServiceClient is the client API for UsersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersServiceClient interface {
	UsersGetPassword(ctx context.Context, in *UsersGetPasswordRequest, opts ...grpc.CallOption) (*UsersGetPasswordResponse, error)
	UsersCreate(ctx context.Context, in *UsersCreateRequest, opts ...grpc.CallOption) (*UsersCreateResponse, error)
	UsersUpdate(ctx context.Context, in *UsersUpdateRequest, opts ...grpc.CallOption) (*UsersUpdateResponse, error)
	UsersList(ctx context.Context, in *UsersListRequest, opts ...grpc.CallOption) (UsersService_UsersListClient, error)
	UsersByID(ctx context.Context, in *UsersByIDRequest, opts ...grpc.CallOption) (*UsersByIDResponse, error)
	UsersDelete(ctx context.Context, in *UsersDeleteRequest, opts ...grpc.CallOption) (*UsersDeleteResponse, error)
}

type usersServiceClient struct {
	cc *grpc.ClientConn
}

func NewUsersServiceClient(cc *grpc.ClientConn) UsersServiceClient {
	return &usersServiceClient{cc}
}

func (c *usersServiceClient) UsersGetPassword(ctx context.Context, in *UsersGetPasswordRequest, opts ...grpc.CallOption) (*UsersGetPasswordResponse, error) {
	out := new(UsersGetPasswordResponse)
	err := c.cc.Invoke(ctx, "/users_pb.UsersService/UsersGetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) UsersCreate(ctx context.Context, in *UsersCreateRequest, opts ...grpc.CallOption) (*UsersCreateResponse, error) {
	out := new(UsersCreateResponse)
	err := c.cc.Invoke(ctx, "/users_pb.UsersService/UsersCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) UsersUpdate(ctx context.Context, in *UsersUpdateRequest, opts ...grpc.CallOption) (*UsersUpdateResponse, error) {
	out := new(UsersUpdateResponse)
	err := c.cc.Invoke(ctx, "/users_pb.UsersService/UsersUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) UsersList(ctx context.Context, in *UsersListRequest, opts ...grpc.CallOption) (UsersService_UsersListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_UsersService_serviceDesc.Streams[0], "/users_pb.UsersService/UsersList", opts...)
	if err != nil {
		return nil, err
	}
	x := &usersServiceUsersListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UsersService_UsersListClient interface {
	Recv() (*UsersListResponse, error)
	grpc.ClientStream
}

type usersServiceUsersListClient struct {
	grpc.ClientStream
}

func (x *usersServiceUsersListClient) Recv() (*UsersListResponse, error) {
	m := new(UsersListResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *usersServiceClient) UsersByID(ctx context.Context, in *UsersByIDRequest, opts ...grpc.CallOption) (*UsersByIDResponse, error) {
	out := new(UsersByIDResponse)
	err := c.cc.Invoke(ctx, "/users_pb.UsersService/UsersByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) UsersDelete(ctx context.Context, in *UsersDeleteRequest, opts ...grpc.CallOption) (*UsersDeleteResponse, error) {
	out := new(UsersDeleteResponse)
	err := c.cc.Invoke(ctx, "/users_pb.UsersService/UsersDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServiceServer is the server API for UsersService service.
type UsersServiceServer interface {
	UsersGetPassword(context.Context, *UsersGetPasswordRequest) (*UsersGetPasswordResponse, error)
	UsersCreate(context.Context, *UsersCreateRequest) (*UsersCreateResponse, error)
	UsersUpdate(context.Context, *UsersUpdateRequest) (*UsersUpdateResponse, error)
	UsersList(*UsersListRequest, UsersService_UsersListServer) error
	UsersByID(context.Context, *UsersByIDRequest) (*UsersByIDResponse, error)
	UsersDelete(context.Context, *UsersDeleteRequest) (*UsersDeleteResponse, error)
}

// UnimplementedUsersServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUsersServiceServer struct {
}

func (*UnimplementedUsersServiceServer) UsersGetPassword(ctx context.Context, req *UsersGetPasswordRequest) (*UsersGetPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsersGetPassword not implemented")
}
func (*UnimplementedUsersServiceServer) UsersCreate(ctx context.Context, req *UsersCreateRequest) (*UsersCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsersCreate not implemented")
}
func (*UnimplementedUsersServiceServer) UsersUpdate(ctx context.Context, req *UsersUpdateRequest) (*UsersUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsersUpdate not implemented")
}
func (*UnimplementedUsersServiceServer) UsersList(req *UsersListRequest, srv UsersService_UsersListServer) error {
	return status.Errorf(codes.Unimplemented, "method UsersList not implemented")
}
func (*UnimplementedUsersServiceServer) UsersByID(ctx context.Context, req *UsersByIDRequest) (*UsersByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsersByID not implemented")
}
func (*UnimplementedUsersServiceServer) UsersDelete(ctx context.Context, req *UsersDeleteRequest) (*UsersDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsersDelete not implemented")
}

func RegisterUsersServiceServer(s *grpc.Server, srv UsersServiceServer) {
	s.RegisterService(&_UsersService_serviceDesc, srv)
}

func _UsersService_UsersGetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersGetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).UsersGetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users_pb.UsersService/UsersGetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).UsersGetPassword(ctx, req.(*UsersGetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_UsersCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).UsersCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users_pb.UsersService/UsersCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).UsersCreate(ctx, req.(*UsersCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_UsersUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).UsersUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users_pb.UsersService/UsersUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).UsersUpdate(ctx, req.(*UsersUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_UsersList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UsersListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UsersServiceServer).UsersList(m, &usersServiceUsersListServer{stream})
}

type UsersService_UsersListServer interface {
	Send(*UsersListResponse) error
	grpc.ServerStream
}

type usersServiceUsersListServer struct {
	grpc.ServerStream
}

func (x *usersServiceUsersListServer) Send(m *UsersListResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _UsersService_UsersByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).UsersByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users_pb.UsersService/UsersByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).UsersByID(ctx, req.(*UsersByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_UsersDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).UsersDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users_pb.UsersService/UsersDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).UsersDelete(ctx, req.(*UsersDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UsersService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "users_pb.UsersService",
	HandlerType: (*UsersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UsersGetPassword",
			Handler:    _UsersService_UsersGetPassword_Handler,
		},
		{
			MethodName: "UsersCreate",
			Handler:    _UsersService_UsersCreate_Handler,
		},
		{
			MethodName: "UsersUpdate",
			Handler:    _UsersService_UsersUpdate_Handler,
		},
		{
			MethodName: "UsersByID",
			Handler:    _UsersService_UsersByID_Handler,
		},
		{
			MethodName: "UsersDelete",
			Handler:    _UsersService_UsersDelete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UsersList",
			Handler:       _UsersService_UsersList_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/pb/users/users.proto",
}
