// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/users/pb/users.proto

package users_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UsersLoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersLoginRequest) Reset()         { *m = UsersLoginRequest{} }
func (m *UsersLoginRequest) String() string { return proto.CompactTextString(m) }
func (*UsersLoginRequest) ProtoMessage()    {}
func (*UsersLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_87300fcef84e6764, []int{0}
}

func (m *UsersLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersLoginRequest.Unmarshal(m, b)
}
func (m *UsersLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersLoginRequest.Marshal(b, m, deterministic)
}
func (m *UsersLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersLoginRequest.Merge(m, src)
}
func (m *UsersLoginRequest) XXX_Size() int {
	return xxx_messageInfo_UsersLoginRequest.Size(m)
}
func (m *UsersLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UsersLoginRequest proto.InternalMessageInfo

func (m *UsersLoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type UsersLoginResponse struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersLoginResponse) Reset()         { *m = UsersLoginResponse{} }
func (m *UsersLoginResponse) String() string { return proto.CompactTextString(m) }
func (*UsersLoginResponse) ProtoMessage()    {}
func (*UsersLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_87300fcef84e6764, []int{1}
}

func (m *UsersLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersLoginResponse.Unmarshal(m, b)
}
func (m *UsersLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersLoginResponse.Marshal(b, m, deterministic)
}
func (m *UsersLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersLoginResponse.Merge(m, src)
}
func (m *UsersLoginResponse) XXX_Size() int {
	return xxx_messageInfo_UsersLoginResponse.Size(m)
}
func (m *UsersLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UsersLoginResponse proto.InternalMessageInfo

func (m *UsersLoginResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UsersLoginResponse) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UsersCreateRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Firstname            string   `protobuf:"bytes,3,opt,name=Firstname,proto3" json:"Firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,4,opt,name=Lastname,proto3" json:"Lastname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersCreateRequest) Reset()         { *m = UsersCreateRequest{} }
func (m *UsersCreateRequest) String() string { return proto.CompactTextString(m) }
func (*UsersCreateRequest) ProtoMessage()    {}
func (*UsersCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_87300fcef84e6764, []int{2}
}

func (m *UsersCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersCreateRequest.Unmarshal(m, b)
}
func (m *UsersCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersCreateRequest.Marshal(b, m, deterministic)
}
func (m *UsersCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersCreateRequest.Merge(m, src)
}
func (m *UsersCreateRequest) XXX_Size() int {
	return xxx_messageInfo_UsersCreateRequest.Size(m)
}
func (m *UsersCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UsersCreateRequest proto.InternalMessageInfo

func (m *UsersCreateRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UsersCreateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UsersCreateRequest) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *UsersCreateRequest) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

type UsersCreateResponse struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersCreateResponse) Reset()         { *m = UsersCreateResponse{} }
func (m *UsersCreateResponse) String() string { return proto.CompactTextString(m) }
func (*UsersCreateResponse) ProtoMessage()    {}
func (*UsersCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_87300fcef84e6764, []int{3}
}

func (m *UsersCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersCreateResponse.Unmarshal(m, b)
}
func (m *UsersCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersCreateResponse.Marshal(b, m, deterministic)
}
func (m *UsersCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersCreateResponse.Merge(m, src)
}
func (m *UsersCreateResponse) XXX_Size() int {
	return xxx_messageInfo_UsersCreateResponse.Size(m)
}
func (m *UsersCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UsersCreateResponse proto.InternalMessageInfo

func (m *UsersCreateResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type UsersUpdateRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Firstname            string   `protobuf:"bytes,3,opt,name=Firstname,proto3" json:"Firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,4,opt,name=Lastname,proto3" json:"Lastname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersUpdateRequest) Reset()         { *m = UsersUpdateRequest{} }
func (m *UsersUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UsersUpdateRequest) ProtoMessage()    {}
func (*UsersUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_87300fcef84e6764, []int{4}
}

func (m *UsersUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersUpdateRequest.Unmarshal(m, b)
}
func (m *UsersUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersUpdateRequest.Marshal(b, m, deterministic)
}
func (m *UsersUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersUpdateRequest.Merge(m, src)
}
func (m *UsersUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UsersUpdateRequest.Size(m)
}
func (m *UsersUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UsersUpdateRequest proto.InternalMessageInfo

func (m *UsersUpdateRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UsersUpdateRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UsersUpdateRequest) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *UsersUpdateRequest) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

type UsersUpdateResponse struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersUpdateResponse) Reset()         { *m = UsersUpdateResponse{} }
func (m *UsersUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UsersUpdateResponse) ProtoMessage()    {}
func (*UsersUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_87300fcef84e6764, []int{5}
}

func (m *UsersUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersUpdateResponse.Unmarshal(m, b)
}
func (m *UsersUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersUpdateResponse.Marshal(b, m, deterministic)
}
func (m *UsersUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersUpdateResponse.Merge(m, src)
}
func (m *UsersUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UsersUpdateResponse.Size(m)
}
func (m *UsersUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UsersUpdateResponse proto.InternalMessageInfo

func (m *UsersUpdateResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

// FIXME:
type UsersListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersListRequest) Reset()         { *m = UsersListRequest{} }
func (m *UsersListRequest) String() string { return proto.CompactTextString(m) }
func (*UsersListRequest) ProtoMessage()    {}
func (*UsersListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_87300fcef84e6764, []int{6}
}

func (m *UsersListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersListRequest.Unmarshal(m, b)
}
func (m *UsersListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersListRequest.Marshal(b, m, deterministic)
}
func (m *UsersListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersListRequest.Merge(m, src)
}
func (m *UsersListRequest) XXX_Size() int {
	return xxx_messageInfo_UsersListRequest.Size(m)
}
func (m *UsersListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UsersListRequest proto.InternalMessageInfo

// FIXME:
type UsersListResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersListResponse) Reset()         { *m = UsersListResponse{} }
func (m *UsersListResponse) String() string { return proto.CompactTextString(m) }
func (*UsersListResponse) ProtoMessage()    {}
func (*UsersListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_87300fcef84e6764, []int{7}
}

func (m *UsersListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersListResponse.Unmarshal(m, b)
}
func (m *UsersListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersListResponse.Marshal(b, m, deterministic)
}
func (m *UsersListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersListResponse.Merge(m, src)
}
func (m *UsersListResponse) XXX_Size() int {
	return xxx_messageInfo_UsersListResponse.Size(m)
}
func (m *UsersListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UsersListResponse proto.InternalMessageInfo

type UsersByIDRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersByIDRequest) Reset()         { *m = UsersByIDRequest{} }
func (m *UsersByIDRequest) String() string { return proto.CompactTextString(m) }
func (*UsersByIDRequest) ProtoMessage()    {}
func (*UsersByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_87300fcef84e6764, []int{8}
}

func (m *UsersByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersByIDRequest.Unmarshal(m, b)
}
func (m *UsersByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersByIDRequest.Marshal(b, m, deterministic)
}
func (m *UsersByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersByIDRequest.Merge(m, src)
}
func (m *UsersByIDRequest) XXX_Size() int {
	return xxx_messageInfo_UsersByIDRequest.Size(m)
}
func (m *UsersByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UsersByIDRequest proto.InternalMessageInfo

func (m *UsersByIDRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type UsersByIDResponse struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Firstname            string   `protobuf:"bytes,3,opt,name=Firstname,proto3" json:"Firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,4,opt,name=Lastname,proto3" json:"Lastname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersByIDResponse) Reset()         { *m = UsersByIDResponse{} }
func (m *UsersByIDResponse) String() string { return proto.CompactTextString(m) }
func (*UsersByIDResponse) ProtoMessage()    {}
func (*UsersByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_87300fcef84e6764, []int{9}
}

func (m *UsersByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersByIDResponse.Unmarshal(m, b)
}
func (m *UsersByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersByIDResponse.Marshal(b, m, deterministic)
}
func (m *UsersByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersByIDResponse.Merge(m, src)
}
func (m *UsersByIDResponse) XXX_Size() int {
	return xxx_messageInfo_UsersByIDResponse.Size(m)
}
func (m *UsersByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UsersByIDResponse proto.InternalMessageInfo

func (m *UsersByIDResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UsersByIDResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UsersByIDResponse) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *UsersByIDResponse) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

type UsersDeleteRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersDeleteRequest) Reset()         { *m = UsersDeleteRequest{} }
func (m *UsersDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*UsersDeleteRequest) ProtoMessage()    {}
func (*UsersDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_87300fcef84e6764, []int{10}
}

func (m *UsersDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersDeleteRequest.Unmarshal(m, b)
}
func (m *UsersDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersDeleteRequest.Marshal(b, m, deterministic)
}
func (m *UsersDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersDeleteRequest.Merge(m, src)
}
func (m *UsersDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_UsersDeleteRequest.Size(m)
}
func (m *UsersDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UsersDeleteRequest proto.InternalMessageInfo

func (m *UsersDeleteRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type UsersDeleteResponse struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersDeleteResponse) Reset()         { *m = UsersDeleteResponse{} }
func (m *UsersDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*UsersDeleteResponse) ProtoMessage()    {}
func (*UsersDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_87300fcef84e6764, []int{11}
}

func (m *UsersDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersDeleteResponse.Unmarshal(m, b)
}
func (m *UsersDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersDeleteResponse.Marshal(b, m, deterministic)
}
func (m *UsersDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersDeleteResponse.Merge(m, src)
}
func (m *UsersDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_UsersDeleteResponse.Size(m)
}
func (m *UsersDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UsersDeleteResponse proto.InternalMessageInfo

func (m *UsersDeleteResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func init() {
	proto.RegisterType((*UsersLoginRequest)(nil), "users_pb.UsersLoginRequest")
	proto.RegisterType((*UsersLoginResponse)(nil), "users_pb.UsersLoginResponse")
	proto.RegisterType((*UsersCreateRequest)(nil), "users_pb.UsersCreateRequest")
	proto.RegisterType((*UsersCreateResponse)(nil), "users_pb.UsersCreateResponse")
	proto.RegisterType((*UsersUpdateRequest)(nil), "users_pb.UsersUpdateRequest")
	proto.RegisterType((*UsersUpdateResponse)(nil), "users_pb.UsersUpdateResponse")
	proto.RegisterType((*UsersListRequest)(nil), "users_pb.UsersListRequest")
	proto.RegisterType((*UsersListResponse)(nil), "users_pb.UsersListResponse")
	proto.RegisterType((*UsersByIDRequest)(nil), "users_pb.UsersByIDRequest")
	proto.RegisterType((*UsersByIDResponse)(nil), "users_pb.UsersByIDResponse")
	proto.RegisterType((*UsersDeleteRequest)(nil), "users_pb.UsersDeleteRequest")
	proto.RegisterType((*UsersDeleteResponse)(nil), "users_pb.UsersDeleteResponse")
}

func init() { proto.RegisterFile("internal/users/pb/users.proto", fileDescriptor_87300fcef84e6764) }

var fileDescriptor_87300fcef84e6764 = []byte{
	// 382 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xd1, 0x4a, 0xeb, 0x40,
	0x10, 0x6d, 0xd3, 0xcb, 0xa5, 0x1d, 0x45, 0x74, 0xfa, 0x52, 0xd2, 0x16, 0x64, 0x51, 0xf0, 0xa9,
	0x05, 0xfd, 0x01, 0xd1, 0x50, 0x08, 0xf4, 0x41, 0x2a, 0x7d, 0x96, 0xd4, 0x0e, 0x12, 0xa8, 0x49,
	0xdc, 0x4d, 0x95, 0xfa, 0x01, 0xfe, 0xa0, 0x3f, 0x24, 0xc9, 0x6e, 0xd2, 0xdd, 0x6c, 0x22, 0x82,
	0xf8, 0x96, 0xdd, 0x99, 0x39, 0x39, 0x67, 0xce, 0x49, 0x60, 0x1c, 0x46, 0x29, 0xf1, 0x28, 0xd8,
	0x4c, 0xb7, 0x82, 0xb8, 0x98, 0x26, 0x2b, 0xf9, 0x30, 0x49, 0x78, 0x9c, 0xc6, 0xd8, 0xcd, 0x0f,
	0x0f, 0xc9, 0x8a, 0x4d, 0xe1, 0x64, 0x99, 0x3d, 0xcf, 0xe3, 0xa7, 0x30, 0x5a, 0xd0, 0xcb, 0x96,
	0x44, 0x8a, 0x2e, 0x74, 0xb3, 0xcb, 0x28, 0x78, 0xa6, 0x41, 0xfb, 0xb4, 0x7d, 0xd1, 0x5b, 0x94,
	0x67, 0x76, 0x0d, 0xa8, 0x0f, 0x88, 0x24, 0x8e, 0x04, 0xe1, 0x11, 0x38, 0xbe, 0xa7, 0x7a, 0x1d,
	0xdf, 0xcb, 0x10, 0xee, 0x02, 0x21, 0xde, 0x62, 0xbe, 0x1e, 0x38, 0x12, 0xa1, 0x38, 0xb3, 0x8f,
	0xb6, 0x82, 0xb8, 0xe5, 0x14, 0xa4, 0xf4, 0x83, 0x97, 0x7e, 0x07, 0x87, 0x23, 0xe8, 0xcd, 0x42,
	0x2e, 0xd2, 0x7c, 0xb0, 0x93, 0x17, 0xf7, 0x17, 0xd9, 0xe4, 0x3c, 0x50, 0xc5, 0x7f, 0x72, 0xb2,
	0x38, 0xb3, 0x73, 0xe8, 0x1b, 0x3c, 0xea, 0xb5, 0xb0, 0x77, 0x45, 0x77, 0x99, 0xac, 0x35, 0xba,
	0x35, 0x8a, 0x4b, 0xfa, 0x4e, 0x85, 0xfe, 0xef, 0x29, 0x16, 0xef, 0x6e, 0xa0, 0x88, 0x70, 0x2c,
	0x4d, 0x09, 0x45, 0xaa, 0x08, 0xb2, 0x7e, 0xe1, 0x6c, 0x7e, 0x27, 0x07, 0x19, 0x53, 0x8d, 0x37,
	0x3b, 0xdf, 0x6b, 0x50, 0xc2, 0x76, 0x6a, 0x50, 0xf6, 0x34, 0x1b, 0xfc, 0x07, 0x72, 0xcf, 0xd4,
	0xaa, 0x3d, 0xda, 0x50, 0xe3, 0xaa, 0xcb, 0xa5, 0x14, 0x5d, 0xf5, 0x14, 0x2f, 0x3f, 0x3b, 0x70,
	0x98, 0xf7, 0xdd, 0x13, 0x7f, 0x0d, 0x1f, 0x09, 0x7d, 0x80, 0x7d, 0x74, 0x71, 0x38, 0x29, 0x3e,
	0x82, 0x89, 0xf5, 0x05, 0xb8, 0xa3, 0xfa, 0xa2, 0xda, 0x62, 0x0b, 0xe7, 0x70, 0xa0, 0x45, 0x07,
	0xab, 0xed, 0x46, 0xb2, 0xdd, 0x71, 0x43, 0xd5, 0x42, 0x93, 0x2e, 0x5b, 0x68, 0x46, 0xf0, 0x2c,
	0x34, 0x33, 0x1a, 0xac, 0x85, 0x33, 0xe8, 0x95, 0xc6, 0xa3, 0x5b, 0x15, 0xb2, 0x4f, 0x88, 0x3b,
	0xac, 0xad, 0x59, 0x38, 0x59, 0x0e, 0x2c, 0x1c, 0x2d, 0x40, 0x16, 0x8e, 0x1e, 0x1c, 0x4d, 0x9d,
	0xb4, 0xcb, 0x52, 0x67, 0x78, 0x6d, 0xa9, 0x33, 0x3d, 0x66, 0xad, 0xd5, 0xff, 0xfc, 0x0f, 0x76,
	0xf5, 0x15, 0x00, 0x00, 0xff, 0xff, 0xe3, 0xba, 0x6b, 0xbc, 0xe2, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UsersServiceClient is the client API for UsersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersServiceClient interface {
	UsersLogin(ctx context.Context, in *UsersLoginRequest, opts ...grpc.CallOption) (*UsersLoginResponse, error)
	UsersCreate(ctx context.Context, in *UsersCreateRequest, opts ...grpc.CallOption) (*UsersCreateResponse, error)
	UsersUpdate(ctx context.Context, in *UsersUpdateRequest, opts ...grpc.CallOption) (*UsersUpdateResponse, error)
	UsersList(ctx context.Context, in *UsersListRequest, opts ...grpc.CallOption) (*UsersListResponse, error)
	UsersByID(ctx context.Context, in *UsersByIDRequest, opts ...grpc.CallOption) (*UsersByIDResponse, error)
	UsersDelete(ctx context.Context, in *UsersDeleteRequest, opts ...grpc.CallOption) (*UsersDeleteResponse, error)
}

type usersServiceClient struct {
	cc *grpc.ClientConn
}

func NewUsersServiceClient(cc *grpc.ClientConn) UsersServiceClient {
	return &usersServiceClient{cc}
}

func (c *usersServiceClient) UsersLogin(ctx context.Context, in *UsersLoginRequest, opts ...grpc.CallOption) (*UsersLoginResponse, error) {
	out := new(UsersLoginResponse)
	err := c.cc.Invoke(ctx, "/users_pb.UsersService/UsersLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) UsersCreate(ctx context.Context, in *UsersCreateRequest, opts ...grpc.CallOption) (*UsersCreateResponse, error) {
	out := new(UsersCreateResponse)
	err := c.cc.Invoke(ctx, "/users_pb.UsersService/UsersCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) UsersUpdate(ctx context.Context, in *UsersUpdateRequest, opts ...grpc.CallOption) (*UsersUpdateResponse, error) {
	out := new(UsersUpdateResponse)
	err := c.cc.Invoke(ctx, "/users_pb.UsersService/UsersUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) UsersList(ctx context.Context, in *UsersListRequest, opts ...grpc.CallOption) (*UsersListResponse, error) {
	out := new(UsersListResponse)
	err := c.cc.Invoke(ctx, "/users_pb.UsersService/UsersList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) UsersByID(ctx context.Context, in *UsersByIDRequest, opts ...grpc.CallOption) (*UsersByIDResponse, error) {
	out := new(UsersByIDResponse)
	err := c.cc.Invoke(ctx, "/users_pb.UsersService/UsersByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) UsersDelete(ctx context.Context, in *UsersDeleteRequest, opts ...grpc.CallOption) (*UsersDeleteResponse, error) {
	out := new(UsersDeleteResponse)
	err := c.cc.Invoke(ctx, "/users_pb.UsersService/UsersDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServiceServer is the server API for UsersService service.
type UsersServiceServer interface {
	UsersLogin(context.Context, *UsersLoginRequest) (*UsersLoginResponse, error)
	UsersCreate(context.Context, *UsersCreateRequest) (*UsersCreateResponse, error)
	UsersUpdate(context.Context, *UsersUpdateRequest) (*UsersUpdateResponse, error)
	UsersList(context.Context, *UsersListRequest) (*UsersListResponse, error)
	UsersByID(context.Context, *UsersByIDRequest) (*UsersByIDResponse, error)
	UsersDelete(context.Context, *UsersDeleteRequest) (*UsersDeleteResponse, error)
}

// UnimplementedUsersServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUsersServiceServer struct {
}

func (*UnimplementedUsersServiceServer) UsersLogin(ctx context.Context, req *UsersLoginRequest) (*UsersLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsersLogin not implemented")
}
func (*UnimplementedUsersServiceServer) UsersCreate(ctx context.Context, req *UsersCreateRequest) (*UsersCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsersCreate not implemented")
}
func (*UnimplementedUsersServiceServer) UsersUpdate(ctx context.Context, req *UsersUpdateRequest) (*UsersUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsersUpdate not implemented")
}
func (*UnimplementedUsersServiceServer) UsersList(ctx context.Context, req *UsersListRequest) (*UsersListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsersList not implemented")
}
func (*UnimplementedUsersServiceServer) UsersByID(ctx context.Context, req *UsersByIDRequest) (*UsersByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsersByID not implemented")
}
func (*UnimplementedUsersServiceServer) UsersDelete(ctx context.Context, req *UsersDeleteRequest) (*UsersDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsersDelete not implemented")
}

func RegisterUsersServiceServer(s *grpc.Server, srv UsersServiceServer) {
	s.RegisterService(&_UsersService_serviceDesc, srv)
}

func _UsersService_UsersLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).UsersLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users_pb.UsersService/UsersLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).UsersLogin(ctx, req.(*UsersLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_UsersCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).UsersCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users_pb.UsersService/UsersCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).UsersCreate(ctx, req.(*UsersCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_UsersUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).UsersUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users_pb.UsersService/UsersUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).UsersUpdate(ctx, req.(*UsersUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_UsersList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).UsersList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users_pb.UsersService/UsersList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).UsersList(ctx, req.(*UsersListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_UsersByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).UsersByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users_pb.UsersService/UsersByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).UsersByID(ctx, req.(*UsersByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_UsersDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).UsersDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users_pb.UsersService/UsersDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).UsersDelete(ctx, req.(*UsersDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UsersService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "users_pb.UsersService",
	HandlerType: (*UsersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UsersLogin",
			Handler:    _UsersService_UsersLogin_Handler,
		},
		{
			MethodName: "UsersCreate",
			Handler:    _UsersService_UsersCreate_Handler,
		},
		{
			MethodName: "UsersUpdate",
			Handler:    _UsersService_UsersUpdate_Handler,
		},
		{
			MethodName: "UsersList",
			Handler:    _UsersService_UsersList_Handler,
		},
		{
			MethodName: "UsersByID",
			Handler:    _UsersService_UsersByID_Handler,
		},
		{
			MethodName: "UsersDelete",
			Handler:    _UsersService_UsersDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/users/pb/users.proto",
}
